#!/usr/bin/env python3
# scripts/lib/strategy_matrix_regen_tsv.py
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Regenerate tests/golden/strategy_matrix/survival.tsv from every values/*.yaml.

Usage: strategy_matrix_regen_tsv.py <expectations.yaml> <values_dir>
"""
import sys
import os

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed; cannot regenerate survival.tsv.", file=sys.stderr)
    sys.exit(1)


def main():
    if len(sys.argv) != 3:
        print(
            "usage: strategy_matrix_regen_tsv.py <expectations.yaml> <values_dir>",
            file=sys.stderr,
        )
        sys.exit(2)

    expect_path = sys.argv[1]
    values_dir = sys.argv[2]

    with open(expect_path) as f:
        expectations = yaml.safe_load(f) or {}

    # Collect per-device dumps.
    device_files = sorted(
        f for f in os.listdir(values_dir) if f.endswith(".yaml")
    )
    devices = [os.path.splitext(f)[0] for f in device_files]

    if not devices:
        # Write header-only TSV.
        tsv_path = os.path.join(os.path.dirname(values_dir), "survival.tsv")
        with open(tsv_path, "w") as out:
            out.write(
                "# capability\tstrategy\t<device columns populated by strategy-matrix --accept>\n"
            )
            out.write(
                "# Y = strategy succeeded on that device/kernel; N = returned non-zero rc;\n"
            )
            out.write("# blank = not measured on that device yet.\n")
            out.write("# Regenerated by scripts/test.sh strategy-matrix --accept.\n")
        print(f"survival.tsv written (no devices yet): {tsv_path}")
        return

    # Load each device yaml.
    device_data = {}
    for fname in device_files:
        dev = os.path.splitext(fname)[0]
        try:
            with open(os.path.join(values_dir, fname)) as f:
                device_data[dev] = yaml.safe_load(f) or {}
        except Exception as e:
            print(f"WARNING: cannot parse {fname}: {e}", file=sys.stderr)
            device_data[dev] = {}

    # Build the full set of (capability, strategy) pairs across all dumps.
    # Use expectations to order capabilities; then append any extras found in
    # device yamls that are not in expectations (future capabilities).
    cap_strat_set: dict[str, set[str]] = {}
    # Seed from expectations order.
    for cap in expectations:
        cap_strat_set.setdefault(cap, set())
    # Walk device yamls.
    for dev in devices:
        caps = (device_data[dev].get("capabilities") or {})
        for cap, capdata in (caps or {}).items():
            cap_strat_set.setdefault(cap, set())
            for s in (capdata or {}).get("strategies", []):
                name = s.get("name")
                if name:
                    cap_strat_set[cap].add(name)

    tsv_path = os.path.join(os.path.dirname(values_dir), "survival.tsv")
    lines = []
    header = "# capability\tstrategy" + "".join(f"\t{d}" for d in devices)
    lines.append(header)

    for cap in cap_strat_set:
        strats = sorted(cap_strat_set[cap])
        if not strats:
            # Capability known from expectations but no strategies seen yet.
            row = f"{cap}\t<none>"
            for dev in devices:
                row += "\t-"
            lines.append(row)
            continue
        for strat in strats:
            row = f"{cap}\t{strat}"
            for dev in devices:
                caps = (device_data[dev].get("capabilities") or {})
                capdata = caps.get(cap) or {}
                found = None
                for s in capdata.get("strategies", []):
                    if s.get("name") == strat:
                        found = s
                        break
                if found is None:
                    row += "\t-"
                elif found.get("enabled"):
                    row += "\tY"
                else:
                    row += "\tN"
            lines.append(row)

    with open(tsv_path, "w") as out:
        out.write("\n".join(lines) + "\n")

    print(f"survival.tsv written: {tsv_path} ({len(devices)} device(s))")


if __name__ == "__main__":
    main()
